[package]
name = "nostr-mls"
version = "0.43.0"
edition = "2021"
description = "A simplified interface to build secure messaging apps on nostr with MLS."
authors = ["Jeff Gardner <j@jeffg.me>", "Yuki Kishimoto <yukikishimoto@protonmail.com>", "Rust Nostr Developers"]
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme = "README.md"
rust-version = "1.74.0"
keywords = ["nostr", "mls", "openmls"]

[dependencies]
hex = { workspace = true, features = ["std"] }
nostr = { workspace = true, features = ["std", "nip44"] }
nostr-mls-storage.workspace = true
openmls = { version = "0.7.0", default-features = false }
openmls_basic_credential = { version = "0.4.0", default-features = false }
openmls_rust_crypto = { version = "0.4.0", default-features = false }
openmls_traits = { version = "0.4.0", default-features = false }
tls_codec = "0.4"
tracing = { workspace = true, features = ["std"] }

[dev-dependencies]
nostr-mls-storage = { workspace = true, features = ["test-utils"] }
nostr-mls-memory-storage.workspace = true
nostr-mls-sqlite-storage.workspace = true
rand = "0.9.2"
tempfile.workspace = true
tokio = { workspace = true, features = ["macros", "rt", "rt-multi-thread"] }
tracing-subscriber = { workspace = true, features = ["env-filter"] }

[[example]]
name = "mls_memory"
path = "examples/mls_memory.rs"

[[example]]
name = "mls_sqlite"
path = "examples/mls_sqlite.rs"
