[workspace]
members = [
    "bindings/nostr-ffi",
    "bindings/nostr-sdk-ffi",
    "crates/nostr",
    "crates/nostr-sdk",
]

[workspace.package]
homepage = "https://github.com/yukibtc/nostr-rs-sdk"
repository = "https://github.com/yukibtc/nostr-rs-sdk.git"
license = "MIT"
rust-version = "1.64.0"

[profile.release]
lto = true
codegen-units = 1