[workspace]
members = [
    "bindings/nostr-sdk-ffi",
    "bindings/nostr-sdk-flutter/rust",
    "bindings/nostr-sdk-js",
    "bindings/uniffi-bindgen",
    "crates/*",
]
exclude = [
    "book/*"
]
default-members = ["crates/*"]
resolver = "2"

[workspace.package]
authors = ["Yuki Kishimoto <yukikishimoto@protonmail.com>", "Rust Nostr Developers"]
homepage = "https://github.com/rust-nostr/nostr"
repository = "https://github.com/rust-nostr/nostr.git"
license = "MIT"
rust-version = "1.70.0"

[workspace.dependencies]
async-trait = "0.1"
async-utility = "0.2"
async-wsocket = { git = "https://github.com/shadowylab/async-wsocket", rev = "4d6a5b1780e65dc657ac36e5990a97c10feef072" }
atomic-destructor = { version = "0.2", default-features = false }
js-sys = "0.3"
negentropy = { version = "0.4", default-features = false }
negentropy-deprecated = { package = "negentropy", version = "0.3", default-features = false }
nostr = { version = "0.35", path = "./crates/nostr", default-features = false }
nostr-connect = { version = "0.35", path = "./crates/nostr-connect", default-features = false }
nostr-database = { version = "0.35", path = "./crates/nostr-database", default-features = false }
nostr-indexeddb = { version = "0.35", path = "./crates/nostr-indexeddb", default-features = false }
nostr-lmdb = { version = "0.35", path = "./crates/nostr-lmdb", default-features = false }
nostr-ndb = { version = "0.35", path = "./crates/nostr-ndb", default-features = false }
nostr-relay-builder = { version = "0.35", path = "./crates/nostr-relay-builder", default-features = false }
nostr-relay-pool = { version = "0.35", path = "./crates/nostr-relay-pool", default-features = false }
nostr-sdk = { version = "0.35", path = "./crates/nostr-sdk", default-features = false }
nostr-zapper = { version = "0.35", path = "./crates/nostr-zapper", default-features = false }
nwc = { version = "0.35", path = "./crates/nwc", default-features = false }
once_cell = { version = "1.20", default-features = false }
serde_json = { version = "1.0", default-features = false }
thiserror = "1.0"
tokio = { version = ">=1.37", default-features = false }
tracing = { version = "0.1", default-features = false }
tracing-subscriber = "0.3"
uniffi = "=0.28.0" # v0.28.1 causes issues when checking MSRV
wasm-bindgen = { version = "0.2", default-features = false }
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", default-features = false }

[patch.crates-io]
# Patch needed to reduce bindings size
bip39 = { git = "https://github.com/rust-bitcoin/rust-bip39", rev = "256a00e7c23c5b2ecc04df90894f60248c8d56d5" }

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
