[workspace]
members = [
    "bindings/nostr-sdk-ffi",
    "bindings/nostr-sdk-js",
    "crates/*",
]
exclude = [
    "book/*"
]
default-members = ["crates/*"]
resolver = "2"

[workspace.package]
authors = ["Yuki Kishimoto <yukikishimoto@protonmail.com>", "Rust Nostr Developers"]
homepage = "https://github.com/rust-nostr/nostr"
repository = "https://github.com/rust-nostr/nostr.git"
license = "MIT"
rust-version = "1.70.0"

[workspace.dependencies]
async-utility = "0.3"
async-wsocket = "0.13"
atomic-destructor = { version = "0.3", default-features = false }
js-sys = "0.3"
negentropy = { version = "0.5", default-features = false }
negentropy-deprecated = { package = "negentropy", version = "0.3", default-features = false }
nostr = { version = "0.38", path = "./crates/nostr", default-features = false }
nostr-connect = { version = "0.38", path = "./crates/nostr-connect", default-features = false }
nostr-database = { version = "0.38", path = "./crates/nostr-database", default-features = false }
nostr-indexeddb = { version = "0.38", path = "./crates/nostr-indexeddb", default-features = false }
nostr-lmdb = { version = "0.38", path = "./crates/nostr-lmdb", default-features = false }
nostr-ndb = { version = "0.38", path = "./crates/nostr-ndb", default-features = false }
nostr-relay-builder = { version = "0.38", path = "./crates/nostr-relay-builder", default-features = false }
nostr-relay-pool = { version = "0.38", path = "./crates/nostr-relay-pool", default-features = false }
nostr-sdk = { version = "0.38", path = "./crates/nostr-sdk", default-features = false }
nwc = { version = "0.38", path = "./crates/nwc", default-features = false }
serde_json = { version = "1.0", default-features = false }
tokio = { version = ">=1.37", default-features = false }
tracing = { version = "0.1", default-features = false }
tracing-subscriber = "0.3"
wasm-bindgen = { version = "0.2", default-features = false }
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", default-features = false }

[patch.crates-io]
# Patch needed to reduce bindings size
bip39 = { git = "https://github.com/yukibtc/rust-bip39", rev = "eade7c56eff5f320e8eb5beee23dd8fb46413938" } # Uses bitcoin_hashes v0.14

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
