[workspace]
members = [
    "bindings/nostr-ffi",
    "bindings/nostr-js",
    "bindings/nostr-sdk-ffi",
    "bindings/nostr-sdk-js",
    "bindings/uniffi-bindgen",
    "crates/*",
]
exclude = [
    "book/*"
]
default-members = ["crates/*"]
resolver = "2"

[workspace.package]
authors = ["Yuki Kishimoto <yukikishimoto@protonmail.com>", "Rust Nostr Developers"]
homepage = "https://github.com/rust-nostr/nostr"
repository = "https://github.com/rust-nostr/nostr.git"
license = "MIT"
rust-version = "1.64.0"

[workspace.dependencies]
async-trait = "0.1"
async-utility = "0.2"
js-sys = "0.3"
nostr = { version = "0.30", path = "./crates/nostr", default-features = false }
nostr-database = { version = "0.30", path = "./crates/nostr-database", default-features = false }
nostr-indexeddb = { version = "0.30", path = "./crates/nostr-indexeddb", default-features = false }
nostr-ndb = { version = "0.30", path = "./crates/nostr-ndb", default-features = false }
nostr-relay-pool = { version = "0.30", path = "./crates/nostr-relay-pool", default-features = false }
nostr-rocksdb = { version = "0.30", path = "./crates/nostr-rocksdb", default-features = false }
nostr-sdk = { version = "0.30", path = "./crates/nostr-sdk", default-features = false }
nostr-signer = { version = "0.30", path = "./crates/nostr-signer", default-features = false }
nostr-sqlite = { version = "0.30", path = "./crates/nostr-sqlite", default-features = false }
nostr-webln = { version = "0.30", path = "./crates/nostr-webln", default-features = false }
nostr-zapper = { version = "0.30", path = "./crates/nostr-zapper", default-features = false }
nwc = { version = "0.30", path = "./crates/nwc", default-features = false }
once_cell = "1.19"
serde_json = { version = "1.0", default-features = false }
thiserror = "1.0"
tokio = { version = "1", default-features = false }
tracing = { version = "0.1", default-features = false }
tracing-subscriber = "0.3"
uniffi = "0.27.1"
wasm-bindgen = { version = "0.2", default-features = false }
wasm-bindgen-futures = "0.4"
web-sys = { version = "0.3", default-features = false }

# Pathces needed to reduce bindings size
[patch.crates-io]
bip39 = { git = "https://github.com/rust-bitcoin/rust-bip39", rev = "256a00e7c23c5b2ecc04df90894f60248c8d56d5" }

[profile.release]
lto = true
codegen-units = 1
panic = "abort"
