[toolchain]
channel = "1.85.0"
profile = "minimal"
components = ["clippy", "rust-docs", "rustfmt"]
targets = [
    "wasm32-wasip2",                # WASI
    "wasm32-unknown-unknown",       # Browser and JS environments
]
