[package]
name = "nostr-indexeddb"
version = "0.44.0"
edition = "2021"
description = "Web's IndexedDB Storage backend for Nostr apps"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme = "README.md"
rust-version.workspace = true
keywords = ["nostr", "database", "indexeddb"]

[package.metadata.docs.rs]
all-features = true
default-target = "wasm32-unknown-unknown"
targets = ["wasm32-unknown-unknown"]
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
hex = { workspace = true, features = ["std"] }
indexed_db_futures = "0.5"
nostr = { workspace = true, features = ["std"] }
nostr-database = { workspace = true, features = ["flatbuf"] }
