[package]
name = "nostr-gossip-memory"
version = "0.44.0"
edition = "2021"
description = "In-memory gossip database"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme = "README.md"
rust-version.workspace = true
keywords = ["nostr", "gossip", "in-memory"]

[dependencies]
indexmap = "2.12"
lru.workspace = true
nostr = { workspace = true, features = ["std"] }
nostr-gossip.workspace = true
tokio = { workspace = true, features = ["sync"] }

[dev-dependencies]
nostr-gossip-test-suite.workspace = true
