[package]
name = "nostr-mls-storage"
version = "0.43.0"
edition = "2021"
description = "Storage abstraction for nostr-mls that wraps OpenMLS storage backends"
authors = ["Jeff Gardner <j@jeffg.me>", "Yuki Kishimoto <yukikishimoto@protonmail.com>", "Rust Nostr Developers"]
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme = "README.md"
rust-version = "1.74.0"
keywords = ["nostr", "mls", "openmls"]

[dependencies]
aes-gcm = "0.10"
nostr = { workspace = true, features = ["std"] }
openmls = { version = "0.7.0", default-features = false }
openmls_traits = { version = "0.4.0", default-features = false }
serde = { workspace = true, features = ["derive"] }
serde_json = { workspace = true, features = ["std"] }

[dev-dependencies]
nostr-mls-sqlite-storage = { version = "0.43", path = "../nostr-mls-sqlite-storage" }
nostr-mls-memory-storage = { version = "0.43", path = "../nostr-mls-memory-storage" }
openmls_memory_storage = "0.4"
