[package]
name = "nostr-sdk-sqlite"
version = "0.12.0"
edition = "2021"
authors = ["Yuki Kishimoto <yukikishimoto@proton.me>"]
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme = "README.md"
rust-version.workspace = true
keywords = ["nostr", "sdk", "db", "sqlite"]

[dependencies]
const_format = "0.2"
log = "0.4"
nostr = { version = "0.12", path = "../nostr" }
r2d2 = "0.8"
r2d2_sqlite = "0.21"
rusqlite = { version = "0.28", features = ["bundled", "serde_json", "url"] }
serde = "1.0"
serde_json = "1.0"
thiserror = "1.0"
