[package]
name = "nostr-relay-builder"
version = "0.37.0"
edition = "2021"
description = "Nostr Relay Builder"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme = "README.md"
rust-version.workspace = true
keywords = ["nostr", "relay", "builder"]

[features]
default = []
tor = ["async-wsocket/tor-launch-service"]

[dependencies]
async-utility.workspace = true
async-wsocket.workspace = true
atomic-destructor.workspace = true
negentropy.workspace = true
nostr = { workspace = true, default-features = false, features = ["std"] }
nostr-database.workspace = true
thiserror.workspace = true
tokio = { workspace = true, features = ["macros", "net", "sync"] }
tracing.workspace = true

[dev-dependencies]
tracing-subscriber = { workspace = true, features = ["env-filter"] }

[[example]]
name = "local-with-hs"
required-features = ["tor"]

[[example]]
name = "mock"
