[package]
name = "nostr-ffi"
version = "0.1.0"
edition = "2021"
authors = ["Yuki Kishimoto <yukikishimoto@proton.me>"]
homepage = "https://github.com/yukibtc/nostr-rs-sdk"
repository = "https://github.com/yukibtc/nostr-rs-sdk.git"
license = "MIT"
rust-version = "1.64"
keywords = ["nostr", "rust", "ffi"]

[lib]
crate-type = ["lib", "cdylib", "staticlib"]

[dependencies]
anyhow = "1.0"
bitcoin_hashes = "0.11"
nostr  = { path = "../../crates/nostr" }
secp256k1 = "0.24"
thiserror = "1.0"
uniffi = "0.21.0"
uniffi_macros = "0.21.0"
url = "2"
uuid = "1.2"

[build-dependencies]
uniffi_build = { version = "0.21.0", features = ["builtin-bindgen"] }
