[package]
name = "nostr-http-file-storage"
version = "0.44.0"
edition = "2021"
description = "Nostr HTTP File Storage client (NIP-96)."
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme = "README.md"
rust-version.workspace = true
keywords = ["nostr", "nip96", "storage", "http"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = []
# Enable support for SOCKS proxy
socks = ["reqwest/socks"]

[dependencies]
nostr = { workspace = true, features = ["std", "rand", "os-rng", "nip96"] }
reqwest = { workspace = true, features = ["json", "multipart", "rustls-tls"] }
tokio = { workspace = true, features = ["sync"] }

[dev-dependencies]
tokio = { workspace = true, features = ["macros", "rt-multi-thread"] }
