[package]
name = "nostr-gossip-sqlite"
version = "0.44.0"
edition = "2021"
description = "Nostr SQLite gossip backend"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme = "README.md"
rust-version.workspace = true
keywords = ["nostr", "gossip", "sqlite"]

[features]
default = ["bundled"]
bundled = ["rusqlite/bundled"]

[dependencies]
async-utility.workspace = true
nostr = { workspace = true, features = ["std"] }
nostr-gossip.workspace = true
rusqlite = { workspace = true, default-features = false }
tokio = { workspace = true, features = ["sync"] }

[dev-dependencies]
nostr-gossip-test-suite.workspace = true
tempfile.workspace = true
