[package]
name = "nostr-browser-signer-proxy"
version = "0.1.0"
edition = "2021"
description = "Proxy to use Nostr Browser signer (NIP-07) in native applications."
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme = "README.md"
rust-version.workspace = true
keywords = ["nostr", "nip07", "browser", "signer", "proxy"]

[dependencies]
atomic-destructor.workspace = true
bytes = "1.10"
http-body-util = "0.1"
hyper = { version = "1.6", features = ["server", "http1"] }
hyper-util = { version = "0.1", features = ["tokio"] }
nostr = { workspace = true, features = ["std"] }
serde = { workspace = true, features = ["std", "derive"] }
serde_json = { workspace = true, features = ["std"] }
tokio = { workspace = true, features = [
  "macros",
  "net",
  "rt",
  "rt-multi-thread",
  "sync",
  "time",
] }
tracing = { workspace = true, features = ["std"] }
uuid = { version = "1.17", features = ["serde", "v4"] }

[dev-dependencies]
nostr = { workspace = true, features = ["nip59"] }
tokio = { workspace = true, features = ["signal"] }
