[package]
name = "nostr-connect"
version = "0.44.0"
edition = "2021"
description = "Nostr Remote Signing (NIP46)"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme = "README.md"
rust-version.workspace = true
keywords = ["nostr", "signer", "nip46", "nostr-connect"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = []
tor = ["nostr-relay-pool/tor"]

[dependencies]
async-utility.workspace = true
nostr = { workspace = true, features = ["std", "rand", "nip04", "nip44", "nip46"] }
nostr-relay-pool.workspace = true
tokio = { workspace = true, features = ["sync"] }
tracing.workspace = true

[dev-dependencies]
dialoguer = "0.11"
tracing-subscriber = { workspace = true, features = ["env-filter"] }
webbrowser = "1.0"

[[example]]
name = "handle-auth-url"

[[example]]
name = "nostr-connect-signer"
