[package]
name = "nostr-memory"
version = "0.44.0"
edition = "2021"
description = "Nostr in-memory events database implementation"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme = "README.md"
rust-version.workspace = true
keywords = ["nostr", "database"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[dependencies]
btreecap.workspace = true
nostr = { workspace = true, features = ["std"] }
nostr-database.workspace = true
tokio = { workspace = true, features = ["sync"] }

[dev-dependencies]
nostr-database-test-suite.workspace = true
