[package]
name = "nostr-sqlite"
version = "0.44.0"
edition = "2021"
description = "SQLite storage backend for nostr apps"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme = "README.md"
rust-version.workspace = true
keywords = ["nostr", "database", "sqlite"]

[package.metadata.docs.rs]
all-features = true
rustdoc-args = ["--cfg", "docsrs"]

[features]
default = []
unbundled = ["sqlx/sqlite-unbundled"]

[dependencies]
nostr = { workspace = true, features = ["std"] }
nostr-database.workspace = true
sqlx = { workspace = true, features = ["json", "migrate", "runtime-tokio", "sqlite"] }

[dev-dependencies]
nostr-database-test-suite.workspace = true
nostr-relay-builder.workspace = true
tempfile.workspace = true
tokio = { workspace = true, features = ["macros", "rt-multi-thread", "time"] }
tracing-subscriber = { workspace = true, features = ["env-filter"] }
