[package]
name = "nostr-sdk-ffi"
version = "0.1.0"
edition = "2021"
authors = ["Yuki Kishimoto <yukikishimoto@proton.me>"]
publish = false

[lib]
name = "nostr_sdk_ffi"
crate-type = ["lib", "cdylib", "staticlib"]

[dependencies]
nostr-ffi  = { path = "../nostr-ffi" }
nostr-sdk  = { path = "../../crates/nostr-sdk", default-features = false, features = ["all-nips", "blocking"] }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
uniffi = { workspace = true }

[build-dependencies]
uniffi = { workspace = true, features = ["build"] }
