[package]
name = "nostr-indexeddb-example"
version = "0.1.0"
edition = "2021"
publish = false

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[dependencies]
nostr-indexeddb = { path = "../../" }
tracing-wasm = "0.2"
wasm-bindgen-futures = "0.4"
web-sys = "0.3"
yew = { version = "0.21", features = ["csr"] }
