[versions]
agp = "8.1.4"
kotlin = "1.9.22"

[libraries]
nostr = { module = "org.rust-nostr:nostr-sdk", version = "0.38.0" }

[plugins]
androidLibrary = { id = "com.android.library", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
