[package]
name = "nostr-sdk-net"
version = "0.23.1"
edition = "2021"
description = "Nostr SDK Network library."
authors = ["Yuki Kishimoto <yukikishimoto@proton.me>"]
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme = "README.md"
rust-version.workspace = true
keywords = ["nostr", "sdk", "net"]

[dependencies]
futures-util = { version = "0.3", default-features = false, features = ["sink", "std"] }
url = { workspace = true }

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
thiserror = { workspace = true }
tokio = { workspace = true, features = ["net", "time"] }
tokio-rustls = "0.24"
tokio-socks = "0.5"
tokio-tungstenite = { version = "0.20", features = ["rustls-tls-webpki-roots"] }
webpki-roots = "0.25"

[target.'cfg(target_arch = "wasm32")'.dependencies]
ws_stream_wasm = "0.7"
