[package]
name = "nostr-sdk-net"
version = "0.20.0"
edition = "2021"
description = "Nostr SDK Network library."
authors = ["Yuki Kishimoto <yukikishimoto@proton.me>"]
homepage.workspace = true
repository.workspace = true
license.workspace = true
readme = "README.md"
rust-version.workspace = true
keywords = ["nostr", "sdk", "net"]

[dependencies]
futures-util = { version = "0.3", default-features = false, features = ["sink", "std"] }
url = "2"

[target.'cfg(not(target_arch = "wasm32"))'.dependencies]
thiserror = "1.0"
tokio = { version = "1.26", default-features = false, features = ["net", "time"] }
tokio-rustls = "0.23"
tokio-socks = "0.5"
tokio-tungstenite = { version = "0.18", features = ["rustls-tls-webpki-roots"] }
webpki = "0.22"
webpki-roots = "0.22"

[target.'cfg(target_arch = "wasm32")'.dependencies]
ws_stream_wasm = "0.7"
